### ISSUE TITLE
Opção para remover o valor se não completar a mascara.

### ISSUE THREAD

**Issue by Tagliatti** [vuejs-tips/vue-the-mask#1]
Olá, atualmente tem essa opção? Não consegui encontrar.
EX: Mask with Clear If Not Match Option do https://igorescobar.github.io/jQuery-Mask-Plugin/

**Comment by neves** [comment]
Pelo que entendi, enquanto a mascara não estiver pronta, ele retorna null ou algo assim?

**Comment by Tagliatti** [comment]
Quando acontece o evento blur do campo ele testa se o valor que está no campo bate com a mascara completa, se não bater ele limpa o campo. Creio ser assim.

**Comment by neves** [comment]
Por enquanto você pode criar uma diretiva separada para isso.
https://jsfiddle.net/neves/2cfhjLq8/
Estou estudando a possibilidade de embutir isso na mascara como uma propriedade boolean.

**Comment by rodrigoroma** [comment]
Alguma novidade? Seria realmente interessante ter essa funcionalidade embutida no plugin.

**Comment by MauricioAires** [comment]
Isso funcionou para mim :+1: 
onBlur={() =>  user.cep.length < 9 && this.setState({user:{...user,cep:''}})}
