### ISSUE TITLE
Usage in non input elements

### ISSUE THREAD

**Issue by renan-taranto** [vuejs-tips/vue-the-mask#11]
Hi,

How are you applying masks to those `<span>` elements in the [docs page](https://vuejs-tips.github.io/vue-the-mask/) placed right of the inputs in the first section? With plain js regex?
The docs codebase is available somewhere so I can check it?

Thanks

**Comment by neves** [comment]
They are just simple binds:
https://github.com/vuejs-tips/vue-the-mask/blob/master/src/docs/field.vue#L5

**Comment by renan-taranto** [comment]
Thanks.

I didn't notice that the docs code is inside the `src`, sorry.
