### ISSUE TITLE
Typescript support

### ISSUE THREAD

**Issue by luca0898** [vuejs-tips/vue-the-mask#113]
Does this library support typescript? I did not find any reference ...

**Comment by JavierPAYTEF** [comment]
I couldn't find typings for this anywhere so I'm assuming it doesn't support typescript.
You can use it anyway but you have to import it differently:

```typescript
// tslint:disable-next-line:no-var-requires
const VueTheMask = require('vue-the-mask');

// To use it globally do:
Vue.use(VueTheMask.default);

// Or, to use the directive in your component
@Component({
  directives: { mask: VueTheMask.mask }
})
export default class YourVueComponent extends Vue {}

// Or, to use the component
@Component({
  components: { TheMask: VueTheMask.TheMask}
})
export default class YourVueComponent2 extends Vue {}
```

**Comment by glodzienski** [comment]
I couldn't find typings as well, but i found another solution. You can check it out bellow.

I created a file named third-parties.d.ts in the _types folder, in my src folder (just for organization)  with the following content:

`declare module 'vue-the-mask';`

You can put more declarations here.

And in my tsconfig.json, i setted my custom type with:

`"typeRoots": [
      "node_modules/@types", "./src/_types/third-parties.d.ts"
    ],`

It worked for me.

**Comment by aaronfulkerson** [comment]
Yo, why'd this get closed? Surely someone can write a type for this.

**Comment by ghost** [comment]
This should cover all use-cases:
```typescript
declare module 'vue-the-mask' {
  import {
    AsyncComponent,
    Component,
    DirectiveFunction,
    DirectiveOptions,
    PluginFunction,
  } from 'vue';

  // Local component:
  const TheMask: Component<any, any, any, any> | AsyncComponent<any, any, any, any>;

  // Local directive:
  const mask: DirectiveFunction | DirectiveOptions;

  // Global plugin / default:
  const VueTheMask: PluginFunction<any> & {
    TheMask: Component<any, any, any, any> | AsyncComponent<any, any, any, any>;
    mask: DirectiveFunction | DirectiveOptions;
  };

  export { TheMask, mask };
  export default VueTheMask;
}
```
