### ISSUE TITLE
Mascara input celular

### ISSUE THREAD

**Issue by hermogenes-ciandt** [vuejs-tips/vue-the-mask#12]
Ola, estou tendo um problema ao usar a mascara no celular.

Estou usando o seguinte codigo 
`<the-mask mask="AAA-####" v-model="placa" placeholder="AAA-0000"></the-mask>`

No computador funciona perfeitamente, porem quando testo no celular acontece um problema.

Quando vou digitar o primeiro numero da placa o caret fica antes do numero.

Assim: ABC-|1

Isso acaba sendo um problema de usabilidade porq o usuario vai digitar direto e a placa fica errada

**Comment by luismiguelprs** [comment]
Mesmo problema aqui.
Android: 6.0.0
Chrome: 59.0.3071.125

**Comment by vjoao** [comment]
Acabei postando uma nova issue, não tinha visto essa. Estou com o mesmo problema.

**Comment by pjaer** [comment]
Also experiencing this on Android 7.0.0 with Chrome 60.0.3112

**Comment by pjaer** [comment]
I have a solution i think, made it work for me and some other masking-project used this as a solution when I googled around. Will make a PR for it

**Comment by luismiguelprs** [comment]
:) good luck @pjaer!

**Comment by pjaer** [comment]
Cant f*cking build project or anything... Can someone make the change for me?
/src/directive.js:54
replace line with
`setTimeout(() => el.setSelectionRange(position, position), 0)`

**Comment by neves** [comment]
@pjaer Does this fix the Android bug?

**Comment by pjaer** [comment]
@neves as far as my testing reached, yes. Havent had time to test it thoroughly though, regressionwise.

**Comment by minatonda** [comment]
https://github.com/vuejs-tips/vue-the-mask/pull/30

Essa parada resolveu aqui pra mim.

**Comment by iamdubx** [comment]
I have the same issue. Android 6.0.1

**Comment by neves** [comment]
Couldn't reproduce the error in any emulator or physical device, but I think it's fixed now with version 0.11.0
