### ISSUE TITLE
Import mask directive using Nuxt

### ISSUE THREAD

**Issue by fabio-rsys** [vuejs-tips/vue-the-mask#122]
Hello guys, I've used this plugin locally on a page and it worked just fine.

Now I'm trying to import the mask directive globally on my project, I use Nuxt.

Have someone done this and could shed some light?

**Comment by brsalviano** [comment]
You can create a plugin inside plugins folder. For exemple:
```
import Vue from 'vue'
import VueTheMask from 'vue-the-mask'
Vue.use(VueTheMask)
```
After, in nuxt.config.js you need to register the plugin:
```
  plugins: [
    '~plugins/vue-the-mask.js'
  ]
```
That's it. It worked for me.

**Comment by vhoyer** [comment]
did this got resolved? it would be cool to know to close the issue :sweat_smile:

**Comment by fabio-rsys** [comment]
Yes it worked just fine, forgot to reply, sorry!

**Comment by davidmarquescoder** [comment]
It works to me:

```
import VueTheMask from 'vue-the-mask';

export default defineNuxtPlugin((nuxtApp) => {
    nuxtApp.vueApp.use(VueTheMask as any);
});
```
