### ISSUE TITLE
Mask phone number 06 and +33

### ISSUE THREAD

**Issue by JonathanVandal** [vuejs-tips/vue-the-mask#124]
Hello, I'm using Vuetify who use vue-the-mask. I'd like to manager 2 types of phone number.
The user can type `06 78 94 56 20` and he can type `+33 6 78 94 56 20`.
I tried this pattern : `['## ## ## ## ##', '+33 # ## ## ## ##']` but it doesn't work.
When I start to type `06 78 94 56` the mask automatically change to `+33 0 67 89 45 6`. 
Even if I type the full number `06 78 94 56 20` I'll get `+33 0 67 89 45 62`

What I need is : 
- if I start typing `06 78 94 56`, I don't want the `+33`
- if I start typing `+33 6 78 94 56 20` I don't want the `06` and when I type 0 I want transform this 0 in +33 

I'd like to get the same behavior as phone mask of [cleave.js](https://nosir.github.io/cleave.js/)

What can I do to do that ?

**Comment by vhoyer** [comment]
could you provide a minimun reprodution of what you tried, perhaps on codesandbox? for us to take a closer look at what is happening? :D

**Comment by khalidabi** [comment]
@JonathanVandal  did u find a solution to this ?

**Comment by JonathanVandal** [comment]
@khalidabi Yep sorry I used cleave.js
