### ISSUE TITLE
Mask phone number with 9 or 8 digits

### ISSUE THREAD

**Issue by gilbertoalbino** [vuejs-tips/vue-the-mask#129]
Hi, is there a way to allow masking an input for both (11)12345-1234 or (11)1234-1234?

**Comment by brdvsoftware** [comment]
> Hi, is there a way to allow masking an input for both (11)12345-1234 or (11)1234-1234?

Na demo do componente tem a máscara do 9º digito brasileiro. 
https://vuejs-tips.github.io/vue-the-mask/

**Comment by gilbertoalbino** [comment]
Ótimo. Não havia visto. Sugestão colocar próximo do Brazil Phone.
Obrigado, trabalho fantástico!
