### ISSUE TITLE
Error in callback for watcher "value"

### ISSUE THREAD

**Issue by gvdonovan** [vuejs-tips/vue-the-mask#13]
I have a master-detail view and a number of the fields are initially null.  The first time an instance encounters null values based on the underlying v-model I get the following:

```
TypeError: Cannot read property 'substring' of null
    at VueComponent.refresh (vue-the-mask.js:141)
    at VueComponent.boundFn [as refresh] (vue.esm.js:124)
    at VueComponent.value (vue-the-mask.js:113)
    at Watcher.run (vue.esm.js:2551)
    at flushSchedulerQueue (vue.esm.js:2329)
    at Array.<anonymous> (vue.esm.js:505)
    at nextTickHandler (vue.esm.js:454)
    at <anonymous>
```

The line in question is 

` var r = t.substring(0, e);`

The errors don't occur subsequent times because the control sets the value to ''.  Changing line 141 to the following seemed to fix my particular issue but I did not run the fix through a battery of regression tests.

`var r = t === null ? '' : t.substring(0, e);`

Regards,

Greg

**Comment by gvdonovan** [comment]
After giving it some thought the control should NOT update the underlying value to '' because this may not always be the desired effect.  It should simply handle nulls.

**Comment by neves** [comment]
Try the latest version v0.10.1

**Comment by gvdonovan** [comment]
Thanks @neves ! Works great.
