### ISSUE TITLE
support token persian char

### ISSUE THREAD

**Issue by jkm-projects** [vuejs-tips/vue-the-mask#134]
hi 
how to use persian char in mask input?

**Comment by RonaldJerez** [comment]
Hi @javadjkm you can pass in your own regexp as the token prop.  The default charset are just A-Z, but if you want internalization support you must set your own regexp for it.

for example (untested pseudo code):

```
let tokens = {
  F: {
    pattern: /[\u0623-\u06CC]/i
  }
}

<the-mask mask="FFFF" :tokens="tokens" />
```

you would need to know the unicode range you want to support, but a quick google search gave me that range for persian, as I dont know the language i dont know if its accurate but try it out. 

Note that vue-the-mask only lets you set tokens on a per field basis.  You can also try out [vue-input-facade](https://ronaldjerez.github.io/vue-input-facade/) which allows you to set the tokens for your whole application at init time.
