### ISSUE TITLE
Typescript support

### ISSUE THREAD

**Issue by andreixk** [vuejs-tips/vue-the-mask#143]
The library has no typescript support. I don't know why the other typescript ticket was closed.

**Comment by gaisinskii** [comment]
@andreixk 

Have you tried `npm install --save @types/vue-the-mask` or `yarn add -D @types/vue-the-mask` ?

It should resolve your problem.

**Comment by Iscrimou** [comment]
> @andreixk
> 
> Have you tried `npm install --save @types/vue-the-mask` or `yarn add -D @types/vue-the-mask` ?
> 
> It should resolve your problem.

This enables to import the lib, but in app.use(VueTheMask) returns the message "Argument of type 'VueTheMaskPlugin' is not assignable to parameter of type 'Plugin<[]>'." and in console shows "Uncaught (in promise) TypeError: o2 is undefined". Any solutions?
