### ISSUE TITLE
Suffix and prefix support

### ISSUE THREAD

**Issue by klarkc** [vuejs-tips/vue-the-mask#15]
There is a way to use this like in the [v-money](https://github.com/vuejs-tips/v-money) component?

**Comment by neves** [comment]
What kind of suffix/prefix would you like?
Check Brazil Phone in https://vuejs-tips.github.io/vue-the-mask/
that has a prefix +55

**Comment by klarkc** [comment]
The behavior is different, with suffix / prefix these values are never removed from the input, even if you select the value, and try to press delete, the prefix/suffix value keeps there.

An example: https://vuejs-tips.github.io/v-money/

**Comment by neves** [comment]
Now I get it. I'll think about it.

**Comment by neves** [comment]
Can you give me some real world samples?

**Comment by neves** [comment]
I couldn't find a solution without a real world situation, so let me know if you find one.

**Comment by Shoroh** [comment]
@neves 
What kind of real world samples do you need?

It's simple, anything can be a prefix, like:

`TMP-123456`

Where `TMP-` is the prefix. So that users be able to put both `TMP-123456` and just `123456` with the same result in the input. The Mask should be able return as masked value (without prefix), and raw value, including `TMP-`.

Something like that :)

**Comment by popod** [comment]
@neves why closing this ? I'd like something like that too :) Is there any solution to do that ? Thanks

**Comment by dukhevych** [comment]
The most popular mask plugin for Vue MUST HAVE this feature.

**Comment by WebKieth** [comment]
Removing this plugin now, cause I need this feature but it hasn't supported and issue was closed without solution

**Comment by WebKieth** [comment]
Solution for prefixes ():
```html
<input ... v-model='fields[key].value'
@input='setPrefix(field, ...arguments)'/>
```
``` javascript
export default {
  methods: {
    setPrefix(field, event) {
       if (!field.prefix) return;
       if (!field.value.startsWith(field.prefix)) {
          this.$set(field, 'value', `${field.prefix} ${event.target.value}`)
       }
    }
  }
}
```
UPD: you dont need event.target.value concat - it calls a bug. Prefix concats with themself without last symbol when you try to delete it. 
Just:
```javascript
export default {
  methods: {
    setPrefix(field) {
       if (!field.prefix) return;
       if (!field.value.startsWith(field.prefix)) {
          this.$set(field, 'value', field.prefix)
       }
    }
  }
}
```
UPD
Last version with all bugfixes and needed mask features
(removing prefix when real value is now empty, and besides - adding when field was empty)
```javascript
        setPrefix(field, event) {
            if (!field.prefix) return;
            const value = event.target.value
            if (value === field.prefix) {
                this.$set(field, 'value', '');
            }
            if (!value.startsWith(field.prefix)) {
                this.$set(field, 'value', `${field.prefix}${value}`)
            }
        }
```

And for postfix the same, but with String.endWith() method.
@neves why you don't add it? This is so simple. And I need it for real world situation - very simple situation - just a phone number. It cant be validate for all needed formats by simple mask - I can validate it only with regex, but only for russian regions, so with +7 undeleteable prefix.
