### ISSUE TITLE
Vuex Warning

### ISSUE THREAD

**Issue by luismiguelprs** [vuejs-tips/vue-the-mask#16]
Hi! I'm getting this warning when I import the component into my project:

`[Vue warn]: Error in callback for watcher "function () { return this._data.$$state }": "Error: [vuex] Do not mutate vuex store state outside mutation handlers."`

**Comment by neves** [comment]
Can you share the line of code that is throwing that error?
I'm not sure that's vue-the-mask related.

**Comment by luismiguelprs** [comment]
Here is the complete console warning that I received.

[Vue warn]: Error in callback for watcher "function () { return this._data.$$state }": "Error: [vuex] Do not mutate vuex store state outside mutation handlers."

(found in <Root>)
warn @ vue.esm.js?65d7:479
handleError @ vue.esm.js?65d7:562
run @ vue.esm.js?65d7:2974
update @ vue.esm.js?65d7:2946
notify @ vue.esm.js?65d7:778
mutator @ vue.esm.js?65d7:833
r @ vue-the-mask.js?3d13:1
t.a @ vue-the-mask.js?3d13:1
t.a @ vue-the-mask.js?3d13:1
callHook$1 @ vue.esm.js?65d7:5750
_update @ vue.esm.js?65d7:5682
updateDirectives @ vue.esm.js?65d7:5656
patchVnode @ vue.esm.js?65d7:5440
patch @ vue.esm.js?65d7:5575
Vue._update @ vue.esm.js?65d7:2424
updateComponent @ vue.esm.js?65d7:2538
get @ vue.esm.js?65d7:2881
run @ vue.esm.js?65d7:2958
flushSchedulerQueue @ vue.esm.js?65d7:2724
(anonymous) @ vue.esm.js?65d7:701
nextTickHandler @ vue.esm.js?65d7:648
vue.esm.js?65d7:566 Error: [vuex] Do not mutate vuex store state outside mutation handlers.
    at assert (vuex.esm.js?edaa:96)
    at Vue$3.store._vm.$watch.deep (vuex.esm.js?edaa:637)
    at Watcher.run (vue.esm.js?65d7:2972)
    at Watcher.update (vue.esm.js?65d7:2946)
    at Dep.notify (vue.esm.js?65d7:778)
    at Array.mutator (vue.esm.js?65d7:833)
    at r (vue-the-mask.js?3d13:1)
    at t.a (vue-the-mask.js?3d13:1)
    at t.a (vue-the-mask.js?3d13:1)
    at callHook$1 (vue.esm.js?65d7:5750)

**Comment by neves** [comment]
What line in your code that if you comment the error stops?

**Comment by luismiguelprs** [comment]
Aparently, the bug occour when the mask comes from a vuex state....
Ex:

`<template>
  <the-mask type="text" v-model="message" :mask="setup.mask" />
</template>

<script>
import {TheMask} from 'vue-the-mask'
export default {
  props: {
    setup: Object
  },
  data: function () {
    return {
      message: null
    }
  },
  components: {
    TheMask
  }
}
</script>

<style lang="scss">
</style>
`

My setup comes from vuex.

**Comment by neves** [comment]
Are you using v-model with the-mask and a data from Vuex?

**Comment by luismiguelprs** [comment]
Yes. Sorry if that is not a good pratice. I'm starting with Vue this week rsrrsrsrs

**Comment by neves** [comment]
Yes, that's a rule of thumb for Vuex.
Happy coding!

**Comment by luismiguelprs** [comment]
Sorry... I guess that I misunderstood your question... my v-model (message) isn't from vuex, just my prop (setup).

**Comment by luismiguelprs** [comment]
I think the warning just happen when the mask is from vuex and is an array.
