### ISSUE TITLE
v-mask directive array not working on v0.11.0-alpha.1

### ISSUE THREAD

**Issue by fmcdigital** [vuejs-tips/vue-the-mask#17]
I'm trying to use the following, but it's not working:

```
<input type="text" name="phone" v-mask="['(##) ####-####', '(##) #####-####']" placeholder="{{ trans('front.phone') }}" />
```

I need to use the directive way because of the validator, but this v-mask array is just working on v0.10 that doesn't support the directive component.

**Comment by neves** [comment]
Try v0.11.0-alpha.2
If it works, let me know so I can move to beta version.

**Comment by fmcdigital** [comment]
Now it's working @neves, thanks for this awesome module.

**Comment by neves** [comment]
Thank you for reporting bugs

**Comment by Jessy93** [comment]
It doesn’t work  for alphanumeric input 
v-mask="['# AA 01', '## AA 01', '### AA 01', '#### AA 01']"
Can someone help me ?
