### ISSUE TITLE
No documentation about using functions in mask property

### ISSUE THREAD

**Issue by maxalmonte14** [vuejs-tips/vue-the-mask#18]
I was trying to use a function in the mask property but the documentation don't explain the correct way to do it, so the result it is not the expected. Would be great improvement to documentation specify as to use functions in mask property.

**Comment by neves** [comment]
Can you provide a use case for this feature?

**Comment by maxalmonte14** [comment]
Well, not exactly, documentation says you can use a String, like this:

`<the-mask :mask="FFFFFF"/>`

Or an Array like this:

`<the-mask :mask="['###', '###-#', '###-##']" />`

But not specify how use a Function. I want to know where I can use Function as mask and how it works.

This is the confusing documentation part for me:

![captura de pantalla de 2017-08-21 12-21-45](https://user-images.githubusercontent.com/12385704/29528855-803db5d4-866b-11e7-86e3-d99b094ab0d1.png)

**Comment by neves** [comment]
The function feature was a attempt to provide your own masker, but that's too complex and specific. I removed from docs but will bring back in case of a real world requirement.

**Comment by skegel13** [comment]
I think functions can be helpful. I wanted to use it to handle Canadian and US zip codes. If the first character typed in is a letter, I want to change the mask to the Canadian zip code, if its a number, change it to US.

The same can be done with handling different credit card formats.
