### ISSUE TITLE
Dynamic mask not working

### ISSUE THREAD

**Issue by vjoao** [vuejs-tips/vue-the-mask#19]
I'm trying to add this dynamic mask:

`['########-#', '##########-#']` so a user can type `14523259-9` and `1012325456-9` but the lib applies only the first mask and I can't type any further.

Any thoughts?

**Comment by vjoao** [comment]
Actually, what I'm trying to do is impossible. Dynamic masks should increase in size only by 1. This should be in the docs.

**Comment by neves** [comment]
Thanks for the tip, maybe I could add a warning in the code.

**Comment by vjoao** [comment]
No problem, amazing lib =)
