### ISSUE TITLE
Problema ao inicializar / Failed to mount component

### ISSUE THREAD

**Issue by evandroabukamel** [vuejs-tips/vue-the-mask#2]
Olá pessoal,

Gostei muito do componente, é o que eu estava procurando, Mas estou com problemas pra usá-lo. Fiz o seguinte:

Baixei o pacote das duas formas:
`npm i -S vue-the-mask`
`npm install vue-the-mask --save-dev`

Na minha página/componente Vue:

```
<the-mask
	:type="'text'" ref="input"
	:mask="['###.###.###-##', '##.###.###/####-##']"
	placeholder="CPF / CNPJ">
</the-mask>
```

```
<script>
import TheMask from 'vue-the-mask';

export default {
	components: { TheMask },
	data() {
	...
```

Mas aparece o seguinte erro no console:

> [Vue warn]: Failed to mount component: template or render function not defined. 
(found in <TheMask>)

Estou fazendo algo de errado? Testei no [JsFiddle](https://jsfiddle.net/neves/r8cL3msn/1/) e funcionou certinho, mas na minha aplicação tenho o tal erro. Estranho, pois tenho alguns componentes que criei e funcionam perfeitamente.

Outra dúvida que tenho é: ele suporta outros atributos do input, como `id`, `class`, `autocomplete` para serem setados por v-bind?

Agradeço.

**Comment by neves** [comment]
O componente estava sendo exportado erroneamente. Tente agora com a versão 0.4.0
Sim, o componente the-mask é um input e suporta os outros atributos.

**Comment by evandroabukamel** [comment]
Opa, deve ser por isso que consegui agora a pouco, baixei ele de novo e funcionou, fazendo a importação global, a local não funcionou. Valeu!  =D

E consegui fazer outra coisa, que é colocar ele dentro de um componente de input customizado que fiz. Deu trabalho mas consegui passar o value do TheMask para o value do meu componente.

**Comment by neves** [comment]
Mostra como vc fez, talvez posso ajudar.

**Comment by evandroabukamel** [comment]
Perdão, funcionou agora, eu estava fazendo coisa errada.
