### ISSUE TITLE
Masking words

### ISSUE THREAD

**Issue by gimyboya** [vuejs-tips/vue-the-mask#20]
I want to create a mask so that the user can input twelve random words. any idea on how to make it with `vue-the-mask` ?

**Comment by vjoao** [comment]
I guess you can't. But, if they are random, why just don't generate them and present to the user?

**Comment by gimyboya** [comment]
that's what i am doing but i need a verification step where i will force the user to enter them again

**Comment by vjoao** [comment]
Give 11 words, let the user type the missing one. It's better UX.

**Comment by neves** [comment]
That's not a mask domain. But if you mean word as a single letter, you can using the mask `mask='SSSSSSSSSSSS'` (twelve alphabetic letters)
