### ISSUE TITLE
$event target not set proverly

### ISSUE THREAD

**Issue by vjoao** [vuejs-tips/vue-the-mask#21]
If you do `<the-mask @input="handler"></the-mask>`

```
handler ($event) {
 // $event here should be an instance of Event
}
```
The argument passed to the handler is the actual value of the input. It should be an instance of Event so you can access the target and its properties. I'll see if I can PR this when I get some time.

**Comment by neves** [comment]
To work with v-model, a custom component needs to respect that behaviour: https://vuejs.org/v2/guide/components.html#Form-Input-Components-using-Custom-Events

But if you need the native event, you can use instead:
`<the-mask @input.native="handler"></the-mask>`

**Comment by vjoao** [comment]
You are right.

**Comment by harol-rodriguez** [comment]
I love vue :') 

'.native'
