### ISSUE TITLE
Question: custom directive pattern

### ISSUE THREAD

**Issue by pmooredesigner** [vuejs-tips/vue-the-mask#22]
Great package!  I see that you can create custom tokens for the component implementation, but using as a directive, am I able to add custom tokens or patterns in some way?  For instance, I was trying to enforce digits, but allow for any number of them.  I was trying things like v-mask="{pattern: /[0-9]+/}" just to see if I could, ha.

Thanks,
Paul

**Comment by neves** [comment]
It has no support for any length mask, but you can use a larger fixed length like:
`v-mask="##########"`
This way it accepts a maximum of 10 digits.

**Comment by pmooredesigner** [comment]
That'll work.  Thanks for your time.

Paul
