### ISSUE TITLE
Mask breaks on mobile

### ISSUE THREAD

**Issue by vjoao** [vuejs-tips/vue-the-mask#23]
Chrome mobile seems to break some behavior when setting the cursor.

With mask `AAA-####`, when you start typing the letters and will type the first number, the cursor is here `( | )`: `ABC-|6`, where it should be here: `ABC-6|`.

Tested on latest Chrome mobile @ Android 7

**Comment by neves** [comment]
see #12

**Comment by iamdubx** [comment]
@neves this is spanish? why do you thin people understand Spanish?

**Comment by neves** [comment]
Sorry, what do you mean by spanish?
By the way, fixed on v0.11.0
