### ISSUE TITLE
Custom tokens

### ISSUE THREAD

**Issue by romanrei** [vuejs-tips/vue-the-mask#24]
Hi.

It's possible to use custom tokens with v-mask directive?

also i need mask number which either can be negative -10 or positive 10. is it possible to do?

**Comment by neves** [comment]
Maybe `https://github.com/vuejs-tips/v-money` can be a option.
What do you think?

**Comment by romanrei** [comment]
Yeah saw it, looks nice, but not for my case.
I just need only positive and negative numbers

**Comment by neves** [comment]
That would not be possible with vue-the-mask, but you can achieve that with v-money without the suffix, prefix and with  precision 0
