### ISSUE TITLE
Include src with package

### ISSUE THREAD

**Issue by ankurk91** [vuejs-tips/vue-the-mask#25]
When you publish the package to npm, you should include `src` folder.

**Benefits**
* One can go and check the implementation within node_modules
* Easy to debug
* Custom build

**Comment by neves** [comment]
The correct way to do that is installing using git:
`yarn add vuejs-tips/vue-the-mask`

**Comment by ankurk91** [comment]
Installing from directly Github is not the recommended way, i don't want my CI server to rely on Github servers.
npm downloads from their own registry.
I think there is no harm publishing `src` folder to npm.
Most of the packages already doing that.

You are building the dist with your configs, but what if someone wants to compile from source.
OR
May be just want to import a single module.
You can have a `.npmignore` to prevent `src/docs` from publishing.

**Comment by neves** [comment]
My main concern is about the package size, a simple node project has > 100MB of node_modules files. But since I can choose which files to publish, I think would be no harm to add the source files.

**Comment by neves** [comment]
Fixed with version 0.11.1
