### ISSUE TITLE
Documentation: tel instead of date or text

### ISSUE THREAD

**Issue by jaysoifer** [vuejs-tips/vue-the-mask#27]
<img width="321" alt="screen shot 2017-08-31 at 13 22 52" src="https://user-images.githubusercontent.com/8316698/29919036-641ac6a2-8e50-11e7-8c13-37d1261969c0.png">

Is this on purpose?

**Comment by iamdubx** [comment]
This way this guy is hiding the fact, that it's doesn't work on mobile. 
This plugin works only if you set `type="tel"`
Otherwise, cursor will have a glitch

**Comment by iamdubx** [comment]
Hey. If you wonder, I found out that all mask libraries have issues on mobiles and they use `type="tel"` to fix them. So this is common for all libraries, not only `vue-the-mask`

**Comment by jaysoifer** [comment]
Thanks for the heads up!

Do you think a _warning_ around these input fields docs would make sense? I, for one, had no idea about it.

**Comment by iamdubx** [comment]
Yeah, I think some mention about this would be awesome. I spend not a one hour to found out. But from other view - I tried probably all mask libraries, and `vue-the-mask` I at the top, at least if you don't need some additional validation, like Cleave does.

**Comment by neves** [comment]
Now there's a mention on docs about input type tel for android devices.
