### ISSUE TITLE
Doesn't work in IE 11

### ISSUE THREAD

**Issue by dubcanada** [vuejs-tips/vue-the-mask#3]
This mask input breaks IE 11, won't let you enter anything into the forms.

**Comment by dubcanada** [comment]
Managed to fix it by changing line

95 of TheMask.vue to

      if (newValue !== '') {
        this.setPosition(position)
      }

from

        this.setPosition(position)

**Comment by neves** [comment]
Can you provide a reproducible example? I tried here in ie 11 and worked.

**Comment by dubcanada** [comment]
Load up IE 11 go to https://vuejs-tips.github.io/vue-the-mask/ and try and type in any of those fields. You can't.

Tried it on my local IE 11 & browerstack IE 11.

**Comment by neves** [comment]
Can you try on IE with the recent released version, 0.8.0?
