### ISSUE TITLE
Can't mask AMEX 

### ISSUE THREAD

**Issue by iamdubx** [vuejs-tips/vue-the-mask#31]
Hi. Thanks for cool plugin!

I can't find a way to mask American Express and Visa simultaneously. 
It has this format `xxxx xxxxxx xxxxx`.  

I thought it could be cool if I could detect some conditional values and use proper mask. For example, if string begins with `37` (AMEX staring numbers), then use one mask, if not then another. 

Will appreciate any thought, how it can be done.

**Comment by neves** [comment]
One solution: https://jsfiddle.net/r8cL3msn/46/
I'll add to the docs.

**Comment by iamdubx** [comment]
@neves perfect, very clean solution! Thank you.
