### ISSUE TITLE
Raw output is not working

### ISSUE THREAD

**Issue by iamdubx** [vuejs-tips/vue-the-mask#32]
I want to output raw data, like in example, but this is not working

```html
<input v-model="phone" masked="false" v-mask="'+38 (0##) ###-##-##'" placeholder="+38 (0××) ×××-××-××"/>
```

**Comment by iamdubx** [comment]
Sorry, found the answer

```
The value returned from directive is always masked!

```

**Comment by melliott03** [comment]
Did you ever get the raw output as in the example?

**Comment by niightly** [comment]
the `masked` attributed shouldn't return `raw` if false?

**Comment by victordanilo** [comment]
> the `masked` attributed shouldn't return `raw` if false?

Unfortunately not
