### ISSUE TITLE
Is there's a way to create min/max values?

### ISSUE THREAD

**Issue by iamdubx** [vuejs-tips/vue-the-mask#33]
For example, I don't want user to be able to type 99/99/9999 in Date of Birth. How to achieve that?

**Comment by iamdubx** [comment]
Solved using tokens. Thanks for awesome plugin!

**Comment by neves** [comment]
I would like to know what was your solution

**Comment by iamdubx** [comment]
@neves I did this for now, but it still should be updated.

```
testToken: {
        m: {
          pattern: /[0-1]/
        },
        M: {
          pattern: /[0-2]/
        },
        d: {
          pattern: /[0-3]/
        },
        D: {
          pattern: /[0-9]/
        },
        y: {
          pattern: /[12]/
        }
      }
```
I can only process one number in regex? How can I limit to 31 for `month` for example?

**Comment by neves** [comment]
Here's one idea: https://jsfiddle.net/r8cL3msn/46/

**Comment by brada1703** [comment]
I know this thread is a bit old... but if someone else has the same problem, you can solve it with:

`v-mask="'dd/mm/yyyy'"`

for example:

`<input type="text" v-mask="'dd/mm/yyyy'">`

Hope that helps someone out there.

**Comment by zhd4n** [comment]
It's possible to make to achive correct dates using value watcher and mask **##/##/####**

 ```
watch: {
        value(newValue, oldValue) {
            const dateParts = newValue.split('/');

            //day
            if (dateParts[0] && dateParts[0].length <= 2 && dateParts[0] > 31) {
                dateParts[0] = 31;
            }

            if (dateParts[0].length === 2 && dateParts[0] < 1) {
                dateParts[0] = '01';
            }

            //month
            if (dateParts[1] && dateParts[1].length <= 2 && dateParts[1] > 12) {
                dateParts[1] = 12;
            }

            if (dateParts[1] && dateParts[1].length === 2 && dateParts[1] < 1) {
                dateParts[1] = '01';
            }
            
            //year
            if (dateParts[2] && dateParts[2].length <= 4 && dateParts[2] > new Date().getFullYear()) {
                dateParts[2] = new Date().getFullYear();
            }

            if (dateParts[2] && dateParts[2].length === 4 && dateParts[2] < 1900) {
                dateParts[2] = '1900';
            }
            

            this.value = dateParts.join('/');
        }
    }
```

**Comment by vascob-77** [comment]
> It's possible to make to achive correct dates using value watcher and mask **##/##/####**
> 
> ```
> watch: {
>        value(newValue, oldValue) {
>            const dateParts = newValue.split('/');
> 
>            //day
>            if (dateParts[0] && dateParts[0].length <= 2 && dateParts[0] > 31) {
>                dateParts[0] = 31;
>            }
> 
>            if (dateParts[0].length === 2 && dateParts[0] < 1) {
>                dateParts[0] = '01';
>            }
> 
>            //month
>            if (dateParts[1] && dateParts[1].length <= 2 && dateParts[1] > 12) {
>                dateParts[1] = 12;
>            }
> 
>            if (dateParts[1] && dateParts[1].length === 2 && dateParts[1] < 1) {
>                dateParts[1] = '01';
>            }
>            
>            //year
>            if (dateParts[2] && dateParts[2].length <= 4 && dateParts[2] > new Date().getFullYear()) {
>                dateParts[2] = new Date().getFullYear();
>            }
> 
>            if (dateParts[2] && dateParts[2].length === 4 && dateParts[2] < 1900) {
>                dateParts[2] = '1900';
>            }
>            
> 
>            this.value = dateParts.join('/');
>        }
>    }
> ```

Ty ;)
