### ISSUE TITLE
mask is not exported in dist/vue-the-mask.js

### ISSUE THREAD

**Issue by simonleclerc** [vuejs-tips/vue-the-mask#37]
Hello,

I'm using vue-the-mask 0.11.1. When importing the mask directive this way:
```
{mask} from "vue-the-mask";
```
 I have this error:
```
Error: 'TheMask' is not exported by node_modules/vue-the-mask/dist/vue-the-mask.js
```

But if I use this import it works fine:
```
import {mask} from "vue-the-mask/src/index.js"; //force the use of src files
```

Is it the intended behavior or I am doing it wrong ?

**Comment by neves** [comment]
I couldn't reproduce the error, here's working fine

**Comment by simonleclerc** [comment]
Can't reproduce it with a minimal test case either. I will dig into my code.

Closing for now.

**Comment by simonleclerc** [comment]
In case someone need it, it was on rollup side. If you use rollup be sure to add this in your config file:
```
plugins:  [
            commonjs({
                namedExports: {
                    'node_modules/vue-the-mask/dist/vue-the-mask.js': [ 'mask' ]
                }
            })
]
```
