### ISSUE TITLE
Moeda

### ISSUE THREAD

**Issue by marcellorg** [vuejs-tips/vue-the-mask#4]
Pretende adicionar mascara para moeda? 
Assim ficaria completo!!!

**Comment by neves** [comment]
Vou fazer um outro componente exclusivo para moeda, vc pode ler mais sobre isso aqui https://github.com/vuejs-tips/vue-the-mask#what-about-money

**Comment by cleitonsouza** [comment]
@neves você já iniciou esse componente pra moeda?
estou precisando e caso tenha iniciado posso tentar colaborar com algo :)

**Comment by neves** [comment]
@cleitonsouza Destas 3, qual vc acha melhor:
https://github.com/vuejs-tips/vue-the-mask#currency

**Comment by cleitonsouza** [comment]
Bom, a com vue tem o problema de ser um componente, acredito que o ideal seja com diretiva, como as mascaras desse repositório.
Além disso, remover no focus e colocar no blur fica estranho pra um usuário leigo.

As com jQuery talvez tenham opções demais, acredito que o sufixo/prefixo, separador e quantidade de caracteres seja o suficiente (além de min/max).

Tentei criar algo mas é realmente complexo, talvez a solução realmente seja a jogada com focus o blur :(
