### ISSUE TITLE
Using mask show numerical keyboard under mobile issue

### ISSUE THREAD

**Issue by chrisribe** [vuejs-tips/vue-the-mask#45]
Hello,

I cannot seem to make the credit card mask work if the (type="number") is set on the tag.
Setting this forces mobile browsers to show the numerical keyboard.

Is there another way to do this??
Thanks
Christian

**Comment by evandroabukamel** [comment]
Use type="tel".

**Comment by chrisribe** [comment]
That does the trick for android and ios !

Was looking into using inputmode="numeric" but browser support is "limited":
https://www.wufoo.com/html5/attributes/23-inputmode.html

Thanks.
Christian
