### ISSUE TITLE
Máscaras para Agência e Conta bancárias

### ISSUE THREAD

**Issue by evandroabukamel** [vuejs-tips/vue-the-mask#5]
Bom dia,

Acho que achei um bug nas máscaras, veja as máscaras que criei:

Agência: ` :mask="['####', '####-#', '####-##']"`
Conta: `:mask="['#####-#', '######-#', '#######-#', '########-#', '#########-#', '###########-#']"`

No caso da agência, a máscara só adiciona um dígido após o traço., Ou seja, só ` '####', '####-#',` funcionam.
Já para a conta, só `'#####-#', '######-#',` funcionam.
Em ambos os casos não é possível adicionar mais dígitos além dessas máscaras que funcionaram.

Pode me dar uma ajudinha com isso? Será que fiz algo errado ou é alguma limitação da biblioteca?

Grato.

**Comment by neves** [comment]
Tudo bom Evandro. Vc está utilizando o recurso de máscara dinâmica para simular algo como máscara monetária. Máscara dinâmica só funciona para um array de 2 opções apenas. Para isso funcionar, precisaria trocar este if por um loop:
https://github.com/vuejs-tips/vue-the-mask/blob/master/src/dynamic-mask.js#L6
Se quiser tentar, fique a vontade. Vou ver tb se tenho alguma idéia para fazer isso.

**Comment by neves** [comment]
Adicionei este recurso na última versão.

**Comment by evandroabukamel** [comment]
Funcionou certinho. Grato.
