### ISSUE TITLE
the cursor jump to end position when edit the front of typed text

### ISSUE THREAD

**Issue by leecz** [vuejs-tips/vue-the-mask#56]
my code:
```js
//html
      <the-mask v-model="form.mac" type="text" mask="FF:FF:FF:FF:FF:FF" :tokens="hexTokens" class="el-input__inner" placeholder="仅支持16进制字符"></the-mask>

//js
      hexTokens: {
        F: {
          pattern: /[0-9a-fA-F]/,
          transform: v => v.toLocaleUpperCase()
        }
      },
```
I input 'AA:AA:AA:AA:AA:AA' ,it's ok,
i want to change it to 'AA:BB:AA:AA:AA:AA'
i move the cursor, delete the second AA, and input a B, then the cursor jump to the end
i can not input 2 BB continuously。

**Comment by Rytiggy** [comment]
Have you made any progress on this, I am experiencing a similar issue.
+1

**Comment by KuzminDmitry** [comment]
Hi, got same problem with it

**Comment by faradayfan** [comment]
I'm experiencing this issue as well.

**Comment by MaxKorolkov** [comment]
I've got this, it's terrible problem for user experience

**Comment by ktquez** [comment]
Any solution?

**Comment by webdeveloper0429** [comment]
same issue...
when I delete any letter on middle, the cursor goes to end

**Comment by brnpimentel** [comment]
same here. Any solutions?

**Comment by solojazz** [comment]
Seems to only happen when v-model is set. A workaround might be setting :value="form" instead, then with v-on:input listen for changes and update your model that way. Feels a bit hacky though

**Comment by clemsontiger** [comment]
@solojazz is right, only happens when v-model is set, which I'd imagine is how many users wish to it. And agree, such a work around is hacky. 

I'm honestly surprise this has not been fixed yet. Originally reported 2 years ago.

**Comment by rajput-saqib** [comment]
You can use v-model with v-mask like this: v-bind:model="form.mac"

**Comment by tjbortz1s** [comment]
I'm getting the same or a similar issue on firefox.  I believe it has something to do with the way vue re-renders controls?

**Comment by singleparadox** [comment]
Please fix :(

**Comment by antonmih** [comment]
Help pls(

**Comment by NikitaLem** [comment]
+1 same error. Still waiting for fix.

**Comment by ngaisteve1** [comment]
Any good workaround?

**Comment by CodingMinds** [comment]
+1 Also waiting for a fix

**Comment by Darkzarich** [comment]
I tried numerous other solutions for masks and there is almost nothing that solved the problem with the caret. The problem lies in how inputs work: if you change the value of an input programmatically it will move the caret to the end of the line, that's just how it works, `v-model` changes `value` programmatically hence why you can see the effect. As a scuffed solution you could do something like "fire on length" thing for your inputs and extend `v-mask` directive to operate the caret for you as in saving previous position etc.

**Comment by ensgenc** [comment]
I found the solution when I tried this package but I still keep testing it.

https://github.com/beholdr/maska
