### ISSUE TITLE
v-on:keyup não é acionado

### ISSUE THREAD

**Issue by ivomarsan** [vuejs-tips/vue-the-mask#6]
Estou noobando aqui quando tento o seguinte trecho de código
```
<the-mask :mask="'#####-###'" v-model="cep" @keyup="buscar"/>
```
Tudo aparenta funcionar normalmente e perfeitamente, exceto o evento keyup que não aciona a função `buscar()` onde realizo uma busca num webservice para autocompletar os outros campos de endereço.

**Comment by neves** [comment]
Sempre que for ouvir um evento nativo em um componente customizado, vc precisa fazer assim:
`<the-mask :mask="'#####-###'" v-model="cep" @keyup.native="buscar"/>`
