### ISSUE TITLE
@keyup not recognized

### ISSUE THREAD

**Issue by evzpav** [vuejs-tips/vue-the-mask#63]
I am trying to use @keyup ( that works with input tag),  however it does enter my function "removeErrorMessage". 
Expected: user clicks submit button on the form, if field is invalid the error message appears. So when user starts typing again (anything), the function removeErrorMessage() would be called to remove the error message.

Please see below:

`	<the-mask :mask="['####-####', '#####-####']" id="number" placeholder="99999-9999" 
					class="input" type="text" v-model="rechargePhoneForm.phoneNumber"
					:masked="false
                                       @keyup="removeErrorMessage()"
      />`

Is there a way to make the @keyup work?

**Comment by evzpav** [comment]
I figured out that :keyup="function()" works instead of @keyup="function()".
Same for v-money lib.

**Comment by harol-rodriguez** [comment]
@evzpav I also tried it like that and it worked but it does not work properly at all
use `@keyup.native`

**Comment by umneeq2** [comment]
> @evzpav I also tried it like that and it worked but it does not work properly at all
> use `@keyup.native`

The .native modifier for v-on is only valid on components but it was used on <input>
