### ISSUE TITLE
vue events on the component

### ISSUE THREAD

**Issue by jlugao** [vuejs-tips/vue-the-mask#7]
hey, I am trying to use this in a CEP field. The thing is I am trying to use the keyup event to fetch data from a restapi, but the event never happens. Is there a way to capture events using this component?

Another thing I've noticed is that there is no easy way of using validation plugins (such as vee-validate) with the field, this would be a nice improvement.

Regards,
João

**Comment by neves** [comment]
You need to use .native to capture native event on custom components:
https://jsfiddle.net/r8cL3msn/3/
I believe the same goes to validation plugins.
