### ISSUE TITLE
Use in none input elements

### ISSUE THREAD

**Issue by saeedvz** [vuejs-tips/vue-the-mask#75]
How to use this package on none input elements like paragraph or label ?

**Comment by quinhone** [comment]
were you able to apply the mask to the label?

**Comment by artemfs** [comment]
You can wrap it in a filter:
```
import masker from 'vue-the-mask/src/masker.js';
import tokens from 'vue-the-mask/src/tokens';

Vue.filter('mask', (value, mask) => masker(value, mask, true, tokens));
```

Usage:
`
{{ '79168166974' | mask('+7 (###) ###-##-##') }}
`

**Comment by mathxbap** [comment]
> You can wrap it in a filter:
> 
> ```
> import masker from 'vue-the-mask/src/masker.js';
> import tokens from 'vue-the-mask/src/tokens';
> 
> Vue.filter('mask', (value, mask) => masker(value, mask, true, tokens));
> ```
> 
> Usage:
> `{{ '79168166974' | mask('+7 (###) ###-##-##') }}`
Thanks!!
