### ISSUE TITLE
Usage as directive

### ISSUE THREAD

**Issue by Darkside73** [vuejs-tips/vue-the-mask#8]
Any chances to use this as directive to integrate with UI frameworks such as vuetify?

**Comment by neves** [comment]
[v-money](https://vuejs-tips.github.io/v-money/) already can be used as directive, but still doesn't work with vuetify because the root element is not the input. If I fix it, I'll try to do the same with vue-the-mask.

**Comment by neves** [comment]
Just fixed it for v-money. I'll let you know if it works for vue-the-mask

**Comment by leok85** [comment]
v-money works great as directive! I am looking forward for the vue-the-mask

**Comment by gfviegas** [comment]
@neves any news? v-mask sucks and i dont wanna stick with it!

**Comment by neves** [comment]
@gfviegas Try the latest alpha version using:
`yarn add vue-the-mask@alpha`

**Comment by gfviegas** [comment]
@neves 

nope... 

console error thrown: 
```javascript
vue-the-mask.js?3d13:1 Uncaught ReferenceError: mask is not defined
    at Object.defineProperty.value (vue-the-mask.js?3d13:1)
    at t (vue-the-mask.js?3d13:1)
    at Object.eval (vue-the-mask.js?3d13:1)
    at t (vue-the-mask.js?3d13:1)
    at e.exports.#.pattern (vue-the-mask.js?3d13:1)
    at eval (vue-the-mask.js?3d13:1)
    at eval (vue-the-mask.js?3d13:1)
    at eval (vue-the-mask.js?3d13:1)
    at Object.<anonymous> (app.js:1830)
    at __webpack_require__ (app.js:660)
```

I've tried several masks combination, with raw input tag and a custom input component but none of them worked.

I'm using v-model and i've tried using the v-mask as you've inserted in the docs `v-mask="'##/##/####'"` to test

**Comment by gfviegas** [comment]
Oh, @neves ,  i've noticed that in docs.vue you've inserted the working example as:
```html
<div class="field" v-mask="'##/##/####'">
    <input type="tel" placeholder="dd/mm/yyyy" />
</div>
```
but it's telling to insert the v-mask on the input tag on the example code. Which one is right?

**Comment by gfviegas** [comment]
@neves  Should I import anything in my .vue file and declare it as a directive?

**Comment by neves** [comment]
Try the latest version, there was a typo.
The correct way to use is in the input.

**Comment by gfviegas** [comment]
@neves the mask simply won't apply.

Do i need to import anything and declare as a directive or a component?

I'm currently doing so globally, in my main file:

```javascript
import VueTheMask from 'vue-the-mask'
Vue.use(VueTheMask)
```

**Comment by nilkesede** [comment]
@neves You may need to update the package version on npm.

@gfviegas use `"vue-the-mask": "vuejs-tips/vue-the-mask"` on your `package.json` to get the version on the master branch. It's working fine!

**Comment by neves** [comment]
@gfviegas Try again 0.11.0-alpha.1
```javascript
import VueTheMask from 'vue-the-mask'
Vue.use(VueTheMask)
```
Or just directive inside component:
```javascript
import {mask} from 'vue-the-mask'
export default {
  directives: {mask}
}
```

**Comment by neves** [comment]
Implemented in version v0.11.0-beta

**Comment by marcellopato** [comment]
Caro @neves , sou meio novato em VueJS e adorei seu pacote, mas gostaria de saber como o uso em uma página Laravel.
Nessa página eu já tenho uma instancia Vue para duplicar linhas de um form e agora quero usar o mask para campos como CNPJ, CPF, etc.

Dentro da tag <script> tenho:

```
import VueTheMask from 'vue-the-mask'
	var app = new Vue({
		el: '#app',
		data: {
			vidas: [
				{
					nome: '',
					grau: '',
					nascimento: ''
				}
			]
		},
		methods: {
			addNovaVida () {
				this.vidas.push({
					nome: '',
					grau:'',
					nascimento: ''
				})
			},
			deleteVida (index) {
				this.vidas.splice(index, 1)
			}
		}
	})
```
E no input onde quero mascarar: 

```
<input type="text" class="form-control" id="CpfCnpj" aria-describedby="CpfCnpj" v-mask="'##.###.###/####-##'">
```

Mas não está rolando. Que bobagem estou fazendo?
Obrigado!

**Comment by emersoncpaz** [comment]
Olá Neves, estou tendo um comportamento estranho do v-mask e se possível gostaria da sua ajuda. Num input já com um dado a ser mascarado a mascará não é aplicada, se aplica apenas após interação no campo. Exemplo: um campo de CPF não carrega o numero formatado, mas após apagar algum digito a mascara é aplicada imediatamente.

**Comment by farnetani** [comment]
@marcellopato você importou o pacote de forma errada.

Faça conforme abaixo que dará certo: 

```
import { mask } from 'vue-the-mask'

export default {
  directives: { mask },
```

**Comment by marcellopato** [comment]
> @marcellopato você importou o pacote de forma errada.
> 
> Faça conforme abaixo que dará certo:
> 
> ```
> import { mask } from 'vue-the-mask'
> 
> export default {
>   directives: { mask },
> ```

Obrigado @farnetani ! Agora deu certinho!
Feliz Natal!
