### ISSUE TITLE
Caret position

### ISSUE THREAD

**Issue by shrpne** [vuejs-tips/vue-the-mask#9]
In US phone example: `+1 (###) ###-####`
If I start to type `1` in a clear input, visible value becomes `+1`. But caret sets after `+` and before `1`.
If next I type `9`, visible input becomes `+1(91`

So typing `19` in clear input leads to`+1(91`, I think it should lead to `+1(9`

**Comment by neves** [comment]
Fixed at https://github.com/vuejs-tips/vue-the-mask/tree/v0.10.0
Thanks for reporting!
